# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 23:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homesort_app', '0004_auto_20161022_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('homelessPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesort_app.HomelessPerson')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesort_app.Shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('homelessPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesort_app.HomelessPerson')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesort_app.Shelter')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='homelessPerson',
        ),
        migrations.RemoveField(
            model_name='record',
            name='shelter',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
